### ISSUE TITLE
Seems to be broken for latest 1.8.3 Spigot

### ISSUE THREAD

**Issue by woutwoot** [mkremins/fanciful#61]
[15:18:49 INFO]: woutwoot issued server command: /Q Working?
[15:18:54 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R2.ChatSerializer
[15:18:54 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[15:18:54 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[15:18:54 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[15:18:54 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[15:18:54 WARN]:        at java.lang.Class.forName0(Native Method)
[15:18:54 WARN]:        at java.lang.Class.forName(Unknown Source)
[15:18:54 WARN]:        at net.amoebaman.util.Reflection.getNMSClass(Reflection.java:64)
[15:18:54 WARN]:        at mkremins.fanciful.FancyMessage.createChatPacket(FancyMessage.java:573)
[15:18:54 WARN]:        at mkremins.fanciful.FancyMessage.send(FancyMessage.java:552)
[15:18:54 WARN]:        at mkremins.fanciful.FancyMessage.send(FancyMessage.java:599)
[15:18:54 WARN]:        at com.woutwoot.tickets.ticket.TicketManager.sendList(TicketManager.java:214)
[15:18:54 WARN]:        at com.woutwoot.tickets.tasks.YourTicketsTask.run(YourTicketsTask.java:20)
[15:18:54 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71)
[15:18:54 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedule
r.java:350)
[15:18:54 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718)
[15:18:54 WARN]:        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[15:18:54 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[15:18:54 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[15:18:54 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:18:54 WARN]: [Tickets] Task #13 for Tickets v1.0 generated an exception
java.lang.NullPointerException
        at mkremins.fanciful.FancyMessage.createChatPacket(FancyMessage.java:573) ~[?:?]
        at mkremins.fanciful.FancyMessage.send(FancyMessage.java:552) ~[?:?]
        at mkremins.fanciful.FancyMessage.send(FancyMessage.java:599) ~[?:?]
        at com.woutwoot.tickets.ticket.TicketManager.sendList(TicketManager.java:214) ~[?:?]
        at com.woutwoot.tickets.tasks.YourTicketsTask.run(YourTicketsTask.java:20) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-dbe012b
-61ef214]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spi
got.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [spigot.jar:git-Spigot-dbe012b-6
1ef214]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-dbe012b-6
1ef214]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-dbe012b-6
1ef214]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-dbe012b
-61ef214]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]

**Comment by mkremins** [comment]
Which version of Fanciful are you using? The latest snapshot version (`0.3.3-SNAPSHOT`) should fix this issue.

**Comment by woutwoot** [comment]
I am using that version. 0.3.3-SNAPSHOT.

**Comment by woutwoot** [comment]
My mistake. My intelij kept using an old version to extract into my plugin jar, that's why I thought I was using the latest version, but I was not... Thanks!
