### ISSUE TITLE
GSON Missing?

### ISSUE THREAD

**Issue by spencerversteeg** [mkremins/fanciful#63]
Stacktrace:

org.bukkit.command.CommandException: Unhandled exception executing command 'youtubers' in plugin LabMain v0.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-b73910a-726656b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-b73910a-726656b]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-b73910a-726656b]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot.jar:git-Spigot-b73910a-726656b]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot.jar:git-Spigot-b73910a-726656b]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-b73910a-726656b]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-b73910a-726656b]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-b73910a-726656b]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_51]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_51]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot.jar:git-Spigot-b73910a-726656b]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-b73910a-726656b]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-b73910a-726656b]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-b73910a-726656b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.NoClassDefFoundError: com/google/gson/JsonParser
        at mkremins.fanciful.FancyMessage.<clinit>(FancyMessage.java:772) ~[?:?]
        at com.thelabmc.labmain.commands.Youtube.onCommand(Youtube.java:35) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-b73910a-726656b]
        ... 14 more
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonParser
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_51]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-b73910a-726656b]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-b73910a-726656b]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
        at mkremins.fanciful.FancyMessage.<clinit>(FancyMessage.java:772) ~[?:?]
        at com.thelabmc.labmain.commands.Youtube.onCommand(Youtube.java:35) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-b73910a-726656b]
        ... 14 more

GSON Is missing?

I am building against the new spigot, Also have Google JSON imported.

Says it's on line 772 of FancyMessage.java

**Comment by DePeep** [comment]
Same with me. I think it is something to do with running it on minecraft 1.8

**Comment by MiniDigger** [comment]
in some older versions gson and other minecraft libs where relocated to net.minecraft.libs or something like that. 
you are saying that you are building against the latest version of spigot. why don't you execute it on the latest version of spigot? infact, your build of spigot is 635 commits behind....
